# Generated by Django 4.2.4 on 2023-08-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='is_actual',
            field=models.BooleanField(verbose_name='Признак текущей версии'),
        ),
    ]
