# Generated by Django 4.2.4 on 2023-08-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_version_is_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='is_actual',
            field=models.BooleanField(default=True, verbose_name='Признак текущей версии'),
        ),
    ]
